"""Add fiction stats

Revision ID: 0334f408ae0a
Revises: fca952ffc7ed
Create Date: 2020-04-23 06:17:55.503778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0334f408ae0a'
down_revision = 'fca952ffc7ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fiction', sa.Column('rank', sa.Integer(), nullable=True))
    op.add_column('fiction', sa.Column('rating_average', sa.Float(), nullable=True))
    op.add_column('fiction', sa.Column('total_views', sa.Integer(), nullable=True))
    op.add_column('fiction', sa.Column('total_votes', sa.Integer(), nullable=True))
    op.add_column('fiction', sa.Column('weekly_views', sa.Integer(), nullable=True))
    op.add_column('fiction', sa.Column('weekly_votes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fiction', 'weekly_votes')
    op.drop_column('fiction', 'weekly_views')
    op.drop_column('fiction', 'total_votes')
    op.drop_column('fiction', 'total_views')
    op.drop_column('fiction', 'rating_average')
    op.drop_column('fiction', 'rank')
    # ### end Alembic commands ###
