"""Initial

Revision ID: 067884a56e02
Revises: 
Create Date: 2019-09-08 20:52:05.310753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '067884a56e02'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('avatar', sa.String(length=500), nullable=True),
    sa.Column('about_me', sa.String(length=1000), nullable=True),
    sa.Column('website', sa.String(length=300), nullable=True),
    sa.Column('theme', sa.String(length=75), nullable=True),
    sa.Column('timezone', sa.String(length=150), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('fiction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('subtitle', sa.String(length=150), nullable=True),
    sa.Column('synopsis', sa.String(length=1000), nullable=False),
    sa.Column('cover_img', sa.String(length=500), nullable=True),
    sa.Column('banner_img', sa.String(length=500), nullable=True),
    sa.Column('words', sa.Integer(), nullable=True),
    sa.Column('website', sa.String(length=300), nullable=False),
    sa.Column('author_placeholder', sa.String(length=100), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=75), nullable=False),
    sa.Column('frequency', sa.Float(), nullable=True),
    sa.Column('approval', sa.Boolean(), nullable=True),
    sa.Column('approval_date', sa.DateTime(), nullable=True),
    sa.Column('approver_id', sa.Integer(), nullable=True),
    sa.Column('updater_id', sa.Integer(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approver_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['updater_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('genre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=75), nullable=False),
    sa.Column('icon', sa.String(length=150), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('updater_id', sa.Integer(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['genre.id'], ),
    sa.ForeignKeyConstraint(['updater_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('updater_id', sa.Integer(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['updater_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('genres',
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.Column('fiction_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fiction_id'], ['fiction.id'], ),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], ),
    sa.PrimaryKeyConstraint('genre_id', 'fiction_id')
    )
    op.create_table('rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stars', sa.Float(), nullable=False),
    sa.Column('subject', sa.String(length=150), nullable=True),
    sa.Column('comment', sa.String(length=5000), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fiction_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fiction_id'], ['fiction.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('submission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submitter_id', sa.Integer(), nullable=False),
    sa.Column('fiction_id', sa.Integer(), nullable=True),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('response', sa.Boolean(), nullable=True),
    sa.Column('comment', sa.String(length=1000), nullable=True),
    sa.Column('updater_id', sa.Integer(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fiction_id'], ['fiction.id'], ),
    sa.ForeignKeyConstraint(['submitter_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['updater_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=False),
    sa.Column('user_agent', sa.String(length=250), nullable=True),
    sa.Column('fiction_id', sa.Integer(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fiction_id'], ['fiction.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vote')
    op.drop_table('submission')
    op.drop_table('rating')
    op.drop_table('genres')
    op.drop_table('tag')
    op.drop_table('genre')
    op.drop_table('fiction')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
