"""Larger about me

Revision ID: 1d70e65c8c96
Revises: 067884a56e02
Create Date: 2020-03-09 11:02:53.661552

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1d70e65c8c96'
down_revision = '067884a56e02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('story')
    op.alter_column('fiction', 'author_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fiction', 'author_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.create_table('story',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=150), nullable=False),
    sa.Column('subtitle', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=150), nullable=True),
    sa.Column('synopsis', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=400), nullable=False),
    sa.Column('cover_img', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=True),
    sa.Column('banner_img', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=True),
    sa.Column('words', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('website', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=300), nullable=False),
    sa.Column('author_placeholder', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('author_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('status', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=75), nullable=False),
    sa.Column('frequency', mysql.FLOAT(), nullable=True),
    sa.Column('approval', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('approval_date', mysql.DATETIME(), nullable=True),
    sa.Column('approver_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('updater_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('updated', mysql.DATETIME(), nullable=False),
    sa.CheckConstraint('`approval` in (0,1)', name='CONSTRAINT_1'),
    sa.ForeignKeyConstraint(['approver_id'], ['user.id'], name='story_ibfk_1'),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], name='story_ibfk_2'),
    sa.ForeignKeyConstraint(['updater_id'], ['user.id'], name='story_ibfk_3'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
