"""Change view.ip to session_id

Revision ID: ad8901675aaf
Revises: 100960102822
Create Date: 2020-03-14 13:24:08.400161

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ad8901675aaf'
down_revision = '100960102822'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('view', sa.Column('session_id', sa.String(length=200), nullable=True))
    op.drop_column('view', 'ip')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('view', sa.Column('ip', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=15), nullable=True))
    op.drop_column('view', 'session_id')
    # ### end Alembic commands ###
