"""Website can be null

Revision ID: fca952ffc7ed
Revises: ba9006ee6ac1
Create Date: 2020-03-23 18:33:44.253074

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fca952ffc7ed'
down_revision = 'ba9006ee6ac1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fiction', 'website',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=300),
               nullable=True)
    op.alter_column('submission', 'website',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=300),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('submission', 'website',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=300),
               nullable=False)
    op.alter_column('fiction', 'website',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=300),
               nullable=False)
    # ### end Alembic commands ###
